In [3]:
import shutil
from pathlib import Path

import lancedb
from lancedb.rerankers import ColbertReranker

from dreamai.ai import ModelName
from dreamai.lance_utils import get_user_query
from dreamai.search_actions import add_data_with_descriptions
from dreamai.settings import CreatorSettings, RAGAppSettings, RAGSettings

creator_settings = CreatorSettings()
rag_settings = RAGSettings()
rag_app_settings = RAGAppSettings()

MODEL = creator_settings.model
LANCE_URI = rag_settings.lance_uri
RERANKER = rag_settings.reranker
HAS_WEB = rag_app_settings.has_web
DATA = "/media/hamza/data2/RFP/docs"

lance_db = lancedb.connect(uri="burr_app/lance/rag/")
reranker = ColbertReranker(RERANKER)

%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
lance_db.table_names()

['ApplicationSecurityStandards',
 'BusinessContinuityDisasterRecovery',
 'CompanySecurityPolicy',
 'EmployeeSecurityPolicy',
 'VendorManagement']

In [6]:
table = lance_db.open_table("VendorManagement")
table.to_pandas()

,name,index,text,vector
0,vendor-management-policy.md,0,# Acme Inc Vendor Management Policy ## Governa...,"[-0.0021941871, -0.018549044, 0.023975216, 0.0..."
1,vendor-management-policy.md,1,c . - Vendors are screened through public reco...,"[-0.011064428, -0.037052516, 0.0054052384, 0.0..."
2,vendor-management-policy.md,2,iewed annually . ## Contracting - Contracts in...,"[0.008778638, -0.005554448, 0.01256999, 0.0427..."
3,vendor-management-policy.md,3,critical solutions . ## Onboarding - Upon cont...,"[-0.0056179445, -0.013572615, 0.008454074, 0.0..."
4,vendor-management-policy.md,4,history are reviewed for increased risk . - V...,"[0.008876327, -0.021689912, 0.013347239, 0.040..."

In [7]:
query = "what is the vendor management system?"
table.search(query=query, query_type="hybrid").rerank(reranker=reranker).limit(10).to_pandas()

/home/hamza/dev/dreamai/.venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
/home/hamza/dev/dreamai/.venv/lib/python3.12/site-packages/sentence_transformers/models/Dense.py:89: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(os.path.join(input_path, "pytorch_model.bin"), map_location=torch.device("cpu"))

,name,index,vector,text,_relevance_score
0,vendor-management-policy.md,0,"[-0.0021941871, -0.018549044, 0.023975216, 0.0...",# Acme Inc Vendor Management Policy ## Governa...,0.924227
1,vendor-management-policy.md,3,"[-0.0056179445, -0.013572615, 0.008454074, 0.0...",critical solutions . ## Onboarding - Upon cont...,0.908225
2,vendor-management-policy.md,1,"[-0.011064428, -0.037052516, 0.0054052384, 0.0...",c . - Vendors are screened through public reco...,0.906300
3,vendor-management-policy.md,4,"[0.008876327, -0.021689912, 0.013347239, 0.040...",history are reviewed for increased risk . - V...,0.892939
4,vendor-management-policy.md,2,"[0.008778638, -0.005554448, 0.01256999, 0.0427...",iewed annually . ## Contracting - Contracts in...,0.875413

In [ ]:
table.search(where="vendor_management_system = 'yes'").to_pandas()

In [5]:
from pydantic import BaseModel, Field, ValidationInfo
from typing import Literal, Self
import sys
from pathlib import Path


# Import the necessary classes and constants
from dreamai.dialog_models import SourcedSentence, SourcedResponse, MAX_RESPONSE_SENTENCES

# Sample data
documents = [
    {"name": "Document 1", "index": 10},
    {"name": "Document 2", "index": 11},
    {"name": "Document 3", "index": 12},
]
context = {"documents": documents, "max_non_sourced_factor": 0.5}

# Create some SourcedSentence instances
sentence1 = SourcedSentence(text="This is the first sentence.", sources=[0, 1])
sentence2 = SourcedSentence(text="This is the second sentence.", sources=[1, 2])
sentence3 = SourcedSentence(text="This is an unsourced sentence.", sources=[-1])

# Create a SourcedResponse
response = SourcedResponse(sentences=[sentence1, sentence2, sentence3])

# Validate the response
validated_response = response.model_validate(response.model_dump(), context=context)

# Print the string representation of the response
print(str(validated_response))

# Print some additional information
print("\nAdditional Information:")
print(f"Is the response sure? {validated_response._sure}")
print(f"Source documents: {validated_response._source_docs}")

# Test a single-sentence response
single_sentence_response = SourcedResponse(sentences=[sentence1])
print("\nSingle Sentence Response:")
print(str(single_sentence_response))

- This is the first sentence. [0, 1]
- This is the second sentence. [1, 2]
- This is an unsourced sentence. [-1]

Additional Information:
Is the response sure? True
Source documents: [[{'name': 'Document 1', 'index': 10}, {'name': 'Document 2', 'index': 11}], [{'name': 'Document 2', 'index': 11}, {'name': 'Document 3', 'index': 12}], []]

Single Sentence Response:
This is the first sentence. [0, 1]

In [12]:
single_sentence_response._sure

True

In [23]:
src = SourcedResponse(
    sentences=[
        SourcedSentence(text="hello", sources=[2]),
        SourcedSentence(text="hello2", sources=[-1]),
        SourcedSentence(text="hello3", sources=[-1]),
    ]
)

In [6]:
print('- Acme Inc has a comprehensive Business Continuity and Disaster Recovery Plan that outlines processes for responding to various disruptions. [0, 1, 2, 3, 4]\n- The plan addresses recovery time objectives (RTOs), recovery sequence, roles and responsibilities, notification procedures, alternate site locations, and detailed recovery procedures. [0, 1, 2, 3, 4]\n- It covers scenarios such as loss of facility, technology, suppliers, and people (pandemic). [0, 1, 2, 3, 4]\n- The plan also includes call trees for crisis management, recovery teams, employees, customers, and public authorities. [0, 1, 2, 3, 4]\n- Failover procedures are documented for network rerouting, DNS updates, and other critical functions. [0, 1, 2, 3, 4]\n- The plan is regularly exercised through walkthroughs, functional exercises, and full interruption tests to ensure its effectiveness. [3, 4]\n- After-action reviews are conducted to document lessons learned and update the plan. [3, 4]\n- The plan is continuously improved by reevaluating recovery capabilities after significant business or technology changes, reviewing supply chain resiliency annually, and monitoring threat intelligence services. [1, 2, 4]\n- The BC/DR program is sponsored by the COO and managed by the BC/DR Manager with support from various departments. [2]\n- A Business Impact Analysis (BIA) is conducted annually to identify critical processes, resources, dependencies, and financial/operational impacts of a disruption. [2]')

- Acme Inc has a comprehensive Business Continuity and Disaster Recovery Plan that outlines processes for responding to various disruptions. [0, 1, 2, 3, 4]
- The plan addresses recovery time objectives (RTOs), recovery sequence, roles and responsibilities, notification procedures, alternate site locations, and detailed recovery procedures. [0, 1, 2, 3, 4]
- It covers scenarios such as loss of facility, technology, suppliers, and people (pandemic). [0, 1, 2, 3, 4]
- The plan also includes call trees for crisis management, recovery teams, employees, customers, and public authorities. [0, 1, 2, 3, 4]
- Failover procedures are documented for network rerouting, DNS updates, and other critical functions. [0, 1, 2, 3, 4]
- The plan is regularly exercised through walkthroughs, functional exercises, and full interruption tests to ensure its effectiveness. [3, 4]
- After-action reviews are conducted to document lessons learned and update the plan. [3, 4]
- The plan is continuously improved by reevaluating recovery capabilities after significant business or technology changes, reviewing supply chain resiliency annually, and monitoring threat intelligence services. [1, 2, 4]
- The BC/DR program is sponsored by the COO and managed by the BC/DR Manager with support from various departments. [2]
- A Business Impact Analysis (BIA) is conducted annually to identify critical processes, resources, dependencies, and financial/operational impacts of a disruption. [2]

In [25]:
src._sure

False

In [2]:
md = MarkdownData.model_validate(
    {"name": "test", "markdown": "lets' gooooooooooooooooooooo"},
    context={"chunk_size": 0, "separators": [r" "]},
)

In [8]:
class ModelA(BaseModel):
    a: int = Field(serialization_alias="a_alias")
    b: str


class ModelB(BaseModel):
    a: int
    b: str

In [9]:
a = ModelA(a=1, b="b")
a.model_dump(by_alias=True)

ValidationError: 1 validation error for ModelA
a_alias
  Field required [type=missing, input_value={'a': 1, 'b': 'b'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing

In [2]:
folder = Path("/media/hamza/data2/RFP/")
qs_md = data_to_md(folder / "questions", chunk_size=0)

In [3]:
docs_md = data_to_md("docs.md", chunk_size=0)

In [8]:
docs_md[0]

MarkdownResult(name='docs.md', markdown='# Acme Inc IT Security Policy\n\n## Access Control\n- All users are assigned unique user IDs and passwords. Sharing of accounts is strictly prohibited. \n- Passwords must be at least 12 characters long and include uppercase, lowercase, numbers and symbols. Passwords expire every 90 days. Previous 12 passwords cannot be reused.\n- Multi-factor authentication (MFA) is required for all remote access to company systems, cloud services, and privileged accounts.\n- User access is granted based on least privilege and job responsibilities. Access is reviewed quarterly and immediately revoked upon role change or termination.\n- Privileged access requires management approval and use of a separate admin account. Admin activities are logged and monitored.\n- Third-party access requires management approval and must use MFA. Access is disabled when no longer needed.\n\n## Data Protection \n- Customer data is classified as confidential and access restricted to authorized personnel. \n- Data is encrypted in transit using TLS 1.2+ and at rest using AES-256. Encryption keys are managed in an HSM.\n- Access to customer data is logged and monitored using a SIEM. Anomalous activity alerts are investigated.  \n- Databases and file shares hosting sensitive data require MFA and are segregated in the network.\n- Confidential data is not permitted on removable media without encryption and management approval. \n- Backups are encrypted and stored in a geographically separate data center. Backup restores are tested quarterly. Backups are retained for 1 year.\n- Data is securely wiped from devices prior to reuse or disposal using DoD 5220.22-M methods. Certification of destruction is obtained.\n\n## Network Security\n- Network is segmented using firewalls to restrict traffic between security zones. Firewall rules are reviewed quarterly.\n- Remote access requires use of an approved VPN with MFA. VPN is restricted to company-managed devices running EDR.\n- Intrusion detection/prevention systems are used to monitor network traffic for malicious activity.\n- All systems run anti-malware software with daily definition updates and real-time scanning.\n- All systems, appliances and applications are hardened per industry benchmarks (CIS, NIST). \n- Security patches are deployed monthly or sooner for critical vulnerabilities, prioritizing externally exposed systems.\n- Internal and external vulnerability scanning is conducted monthly. Critical vulnerabilities are remediated within 30 days.\n- Penetration testing is conducted quarterly by an independent third party. Findings are triaged and remediated based on risk.\n- Web application firewalls are used for public-facing web applications.\n- A CASB monitors all cloud service usage for data exfiltration and anomalous activity.\n\n## Endpoint Security\n- All workstations and laptops run centrally managed EDR/MDR with logging enabled. \n- Full disk encryption is required using BitLocker (Windows) or FileVault (Mac).\n- USB ports are restricted. Only approved devices permitted.\n- Software installation is restricted. Users cannot disable security software.\n- Screen locks are enforced after 10 minutes of inactivity.\n\n## Physical Security\n- Access to offices, data centers and wiring closets is restricted to authorized personnel using badge readers and PINs.\n- Doors automatically close and lock. Badge activity is logged and monitored.\n- Visitors must sign a log, wear a badge, and be escorted at all times.\n- Offices use 24/7 monitored alarm systems with security cameras at entry/exit points.\n- Environmental controls include redundant commercial power, UPS, generators, and fire suppression systems. \n- Wiring is enclosed in conduit. Redundant ISP connections are used.\n\n## Incident Response\n- A formal incident response plan is maintained that defines alert severity levels, roles and responsibilities, investigation procedures, containment steps, recovery, and internal/external communication protocols.\n- The plan is tested annually in a tabletop exercise and updated based on lessons learned.\n- A 24/7 phone number and email alias are provided for reporting suspected incidents. \n- Incident response personnel maintain security clearances and receive annual training.\n- Cyber insurance is maintained to cover incident response, forensics, notification costs, etc.\n\n## Asset Management\n- A centralized inventory is maintained of all IT hardware and software assets, including physical location, assigned owner, and supported status.  \n- New assets are added to inventory upon procurement and removed upon disposal.\n- Inventory audits are conducted annually to verify accuracy.\n- Unsupported systems are not permitted on the network unless isolated and necessary for business. A remediation plan is required.\n\n## Risk Management\n- A steering committee of senior leadership meets quarterly to review top risks to information assets.\n- An annual risk assessment is conducted to identify threats/vulnerabilities and assess risk based on likelihood and impact.\n- Risks are treated with security controls or accepted by management where risk exceeds risk appetite.\n\n## HR Security\n- Background checks are conducted for new hires in accordance with local laws, including criminal history and employment verification.\n- Employees sign a confidentiality agreement covering data protection and IP.\n- Employees complete mandatory annual training on acceptable use, data handling and reporting security incidents.\n- Disciplinary procedures are enforced for policy violations up to termination.\n\n## Compliance\n- Acme Inc certifies compliance with applicable industry standards, e.g. PCI DSS, SOC 2, ISO 27001, HIPAA. \n- Audits are conducted annually by an independent assessor. Audit findings are remediated.\n- A compliance manager monitors relevant laws and regulations for changes.\n\n## Policy Management\n- This policy is reviewed and updated annually and upon significant changes.\n- Supporting control procedures are maintained by asset owners.\n- Policy exceptions require CISO approval and are reviewed annually.  \n- Employees certify acknowledgement of this policy annually.\n\n\n\n# Acme Inc Employee Security Policy\n\n## Acceptable Use\n- Company resources are for business use only. Personal use is prohibited. \n- Users must comply with applicable laws and regulations. Illegal content and copyright infringement are prohibited.\n- Users must not attempt to circumvent security controls, access confidential data without authorization, or install unauthorized software/hardware.\n\n## Confidentiality\n- Employees must protect confidential company information from unauthorized disclosure.\n- Confidential data must not be shared with external parties without an NDA. \n- Confidential data must not be posted publicly or stored on unapproved cloud services.\n- Confidential hard copy documents must be shredded when no longer needed.\n\n## Data Handling  \n- Data must be classified based on sensitivity and labelled.\n- Need to know and least privilege principles must be followed.\n- Customer PII and cardholder data must be encrypted in transit and at rest.\n- PII must only be collected and used with consent and for the specified purpose.\n\n## Secure Development\n- All code must be tested for vulnerabilities before production release.\n- OWASP Top 10 risks must be mitigated.\n- Secrets must not be hardcoded. A secrets management solution must be used.\n- Open source code must come from trusted sources. SCA tools must be used to scan for vulnerabilities.\n\n## Physical Security\n- Employees must wear a badge on premises.\n- Visitors must be logged and escorted.\n- Sensitive areas must remain locked.\n- Employees must not tailgate through secure doors.\n\n## Workstation Security  \n- Workstations must not be left unattended. Screens must be locked when not in use.\n- MFA must be used.  \n- Workstations must run current AV and be patched within 30 days.\n- Full disk encryption must be enabled.\n- Files must be stored on network shares, not locally.\n- Clear desk policy must be followed.\n\n## Remote/Mobile\n- Company laptops and mobile devices must be used to access company data. \n- MFA and VPN must be used for remote access.\n- Public wifi must not be used without the VPN.\n- Laptops and mobile devices must be physically secured at all times.\n- Lost/stolen devices must be reported immediately.\n\n## Incident Reporting\n- Employees must immediately report security incidents by calling the security hotline or emailing security@acme.com.\n- Incidents include malware, unauthorized account usage, data loss/theft, and physical security breaches.\n- Employees must not attempt to investigate on their own.\n\n## Privacy\n- Employees must not access or disclose customer or employee personal data without authorization.\n- Employees must complete data privacy training before accessing PII.\n- Marketing must honor opt-out requests.\n\n## Disciplinary Action\n- Violation of this policy may result in disciplinary action up to and including termination.\n- Employees must report violations to their manager or HR.\n\n\n\n# Acme Inc Business Continuity and Disaster Recovery Plan\n\n## Program Governance\n- The BC/DR program is sponsored by the COO with oversight from a steering committee of senior leadership.\n- The program is managed by the BC/DR Manager with support from IT, HR, facilities, and business units.\n- A BC/DR policy established program requirements, roles and responsibilities, and KPIs.\n\n## Business Impact Analysis \n- A BIA is conducted annually by interviewing business process owners. \n- The BIA identifies critical processes, resources, dependencies, and financial/operational impacts of a disruption over time. \n- Maximum tolerable downtime (MTD) and recovery time objectives (RTO) are determined for each process.\n- Critical vendors are identified and recovery requirements defined in contracts.\n\n## Risk Assessment\n- A risk assessment is conducted annually to identify and assess natural and man-made threats to business operations.\n- Risks are scored based on likelihood and impact to people, property, technology and reputation. \n- Risk treatment options are evaluated including new controls, alternate suppliers or sites, and risk transfer.\n\n## Strategy\n- Critical processes are recovered in priority order based on RTOs and dependencies. Non-critical processes are deferred until resources permit.\n- Primary systems and data are replicated in near real-time to a hot DR site in a separate region using a dedicated network link.\n- Alternate office space and equipment are pre-staged under contract to enable quick activation and relocation. Mobile recovery units are available if needed.\n- SaaS and cloud infrastructure are used where possible to increase resiliency. Failover is tested monthly.\n- Employees are equipped to work remotely via secure laptops and VDI. Capacity is monitored.\n\n## Plan\n- The BC/DR plan documents process RTOs, recovery sequence, roles and responsibilities, notification procedures, alternate site locations, and detailed recovery procedures.\n- Plans are maintained for loss of facility, technology, suppliers, and people (pandemic).\n- Call trees are maintained with primary and secondary contacts for crisis management, recovery teams, employees, customers and public authorities.\n- Failover procedures are documented for network rerouting, DNS updates, etc.\n\n## Exercising\n- Walkthrough exercises are conducted quarterly with recovery teams to validate roles and procedures.\n- Annual functional exercises are conducted with business teams to test alternate operations, e.g. paper processing, manual workarounds, and team coordination. \n- A full interruption test is conducted annually rotating between loss scenarios (facility, data center, etc.) Failover to the DR site and reconstitution to production is performed.\n- After-action reviews are conducted to document lessons learned and update plans. KPIs are measured and reported to management.\n\n## Continuous Improvement  \n- Recovery capabilities are re-evaluated after significant business or technology changes. \n- New products and services require BC/DR plans before launch.\n- Supply chain resiliency is reviewed annually including sole-source suppliers, geopolitical risk and transportation risk.\n- Information feeds from threat intelligence services and public agencies are monitored for emerging threats.\n- Budget and staffing for the BC/DR program are reviewed annually as part of the business planning cycle.\n\n\n\n# Acme Inc Vendor Management Policy\n\n## Governance\n- A vendor management office (VMO) is established within procurement to govern vendor relationships.\n- The VMO maintains policies and procedures for vendor selection, contracting, onboarding, performance management, and offboarding.\n- Vendor risk is overseen by the risk committee and CISO. High risk vendors require CISO approval.\n- An approved vendor list is maintained with risk ratings, spend tier, and primary contacts.\n\n## Due Diligence\n- RFP/RFIs must include security and privacy requirements. Vendor responses are evaluated by infosec.\n- Vendors are screened through public records, financial reports, D&amp;B reports, reference checks, etc.\n- A vendor security assessment is conducted using industry standard questionnaires (e.g. SIG, CAIQ). Responses are validated on site for high risk vendors.\n- Vendors processing confidential data are assessed for compliance with regulatory standards (PCI, HIPAA, GDPR, etc.). Evidence of compliance is obtained. \n- Vendors are assigned an inherent risk rating based on access to data, business criticality, and outsourced controls. Risk ratings are reviewed annually.\n\n## Contracting\n- Contracts include security and privacy terms such as compliance requirements, right to audit, security incident notification, data ownership, and termination rights.\n- Data protection addendums and business associate agreements are required where applicable.  \n- Contracts specify service levels (SLA), recovery time objectives (RTO), and penalties for non-performance.\n- Contracts define the process to receive vulnerability reports and remediate vendor products.\n- Source code escrow is required for critical solutions.\n\n## Onboarding\n- Upon contract signing, vendors are provisioned in procurement and AP systems.\n- Security configurations are applied prior to granting access to systems and data.\n- Secure data transfer methods are established for data exchanges.\n\n## Ongoing Management\n- Vendor performance to SLAs is monitored, including security metrics. Dashboards are reviewed monthly.\n- High risk vendors provide independent audit reports annually (SOC 2, ISO 27001, PCI ROC, etc.)\n- Material changes to vendor\'s security posture or breach history are reviewed for increased risk.\n- Vulnerability scan data is obtained monthly for hosted/cloud vendors. \n- Business continuity and DR plans are obtained annually and tested where feasible.\n- Vendor security incidents are scored for impact and root cause is determined. The VMO participates in after-action reviews.\n\n## Termination\n- Upon contract termination, access is revoked, data is returned or destroyed, and equipment is returned.\n- A service transition plan is enacted to prevent disruption, including knowledge transfer and migration to a new solution/vendor.\n- Final invoices are paid and vendor records are archived per record retention policy.\n- Lessons learned are documented and factored into future sourcing decisions.\n\n\n\n# Acme Inc Application Security Standards\n\n## Secure SDLC\n- Projects must follow the approved SDLC including security requirements, threat modeling, secure coding, code review and testing.\n- The security champion reviews user stories for security impact and participates in design reviews.\n- All code changes require peer review. Merges to the main branch require 2 approvals.\n- Major releases require signoff from the security architect.\n- DevSecOps tools are used to automate security scans including SAST, DAST, SCA and container scanning. Builds fail if high severity issues are found.\n\n## Authentication\n- Applications must not accept credentials in URLs or logs.\n- MFA is required for admin access and business critical apps. FIDO2 or push notification is preferred.\n- Service accounts must not be shared. Passwords must be vaulted and rotated every 90 days.\n- Authentication failures are logged. Accounts are locked after 5 failed attempts for 30 minutes.\n- Forgot password flows use time-bound secure token sent via a side channel.\n\n## Session Management\n- Stateless JWT access and refresh tokens must be used, not server-side sessions.\n- JWTs must be signed using the RS256 alg. HS256 is prohibited.\n- The access token must be short-lived (5-10 min). The refresh token expires in 8 hours.  \n- Refresh tokens are only sent to the token endpoint. Access tokens are not stored.\n- Refresh tokens are invalidated on logout. Tokens are single use.\n\n## Access Control\n- Roles and permissions are defined using RBAC. Access is granted to roles, not users.\n- Roles are reviewed quarterly and follow least privilege. \n- Fine-grained, feature level permissions are used for sensitive functions.\n- The application enforces access control on every request. Access failures return "403 Forbidden".\n- DOM-based access control is not used.  \n- API endpoints authorize the calling application and token.\n\n## Input Validation\n- All input is untrusted and must be validated for type, length, format and range.\n- Validation is performed on the server. Client-side validation is only for UX.\n- Data is normalized and output encoded to prevent XSS, SQL injection and other injection flaws.\n- Parameterized queries or ORM frameworks are used.\n- SSRF protections are in place. URL whitelisting, DNS resolution and response filtering are used.\n- XML input is validated against XXE using a local static DTD.\n- Deserialization of untrusted data is prohibited.\n\n## File Uploads\n- Only allow whitelisted file types. Validate type by inspecting file headers, not extension.\n- Set a max file size to prevent large files from overwhelming the system.\n- Generated filenames should not use user input.\n- Files must be scanned by AV before being stored or opened.\n- File downloads should use the Content-Disposition: attachment header.\n\n## Cryptography\n- Don\'t roll your own crypto. Only use approved crypto libraries.  \n- Use authenticated encryption modes (GCM). Avoid unauthenticated (CBC).\n- 2048-bit or larger RSA keys and 256-bit or larger ECC keys must be used.\n- Secrets must be generated using a CSPRNG.\n- Password storage must use Argon2, PBKDF2, scrypt or bcrypt.\n\n## Error Handling  \n- Exceptions must be caught and handled gracefully.\n- Fail securely. Denied access should return a generic 403 error.\n- Sensitive data must not be logged or returned in error messages.  \n- Use HTTP 400-series for client errors, 500-series for server errors.\n\n## Logging\n- Log authentication events, access control failures, input validation failures and exceptions.\n- Include timestamp, username, IP address, and detailed event info.\n- Log to a separate server. Restrict access to logs.\n- Disallow sensitive data in logs. Mask or truncate as needed.\n\n## Response Headers\n- X-Frame-Options: SAMEORIGIN\n- X-Content-Type-Options: nosniff\n- Content-Security-Policy with strict policies\n- Strict-Transport-Security with min 1 year max-age  \n- Cache-Control, Pragma: no-cache on sensitive pages\n\n', chunks=[])

In [5]:
Path("docs.md").write_text("\n\n".join([d.markdown for d in docs_md]))

19363

In [ ]:
If it is asked to assist with tasks involving the expression of views held by a significant number of people, Claude provides assistance with the task regardless of its own views. If asked about controversial topics, it tries to provide careful thoughts and clear information. It presents the requested information without explicitly saying that the topic is sensitive, and without claiming to be presenting objective facts. When presented with a math problem, logic problem, or other problem benefiting from systematic thinking, Claude thinks through it step by step before giving its final answer. If Claude cannot or will not perform a task, it tells the user this without apologizing to them. It avoids starting its responses with “I’m sorry” or “I apologize”. If Claude is asked about a very obscure person, object, or topic, i.e. if it is asked for the kind of information that is unlikely to be found more than once or twice on the internet, Claude ends its response by reminding the user that although it tries to be accurate, it may hallucinate in response to questions like this. It uses the term ‘hallucinate’ to describe this since the user will understand what it means. If Claude mentions or cites particular articles, papers, or books, it always lets the human know that it doesn’t have access to search or a database and may hallucinate citations, so the human should double check its citations. Claude is very smart and intellectually curious. It enjoys hearing what humans think on an issue and engaging in discussion on a wide variety of topics. Claude uses markdown for code. Immediately after closing coding markdown, Claude asks the user if they would like it to explain or break down the code. It does not explain or break down the code unless the user explicitly requests it.Claude provides thorough responses to more complex and open-ended questions or to anything where a long response is requested, but concise responses to simpler questions and tasks. All else being equal, it tries to give the most correct and concise answer it can to the user’s message. Rather than giving a long response, it gives a concise response and offers to elaborate if further inforpmation may be helpful.

Claude is happy to help with analysis, question answering, math, coding, creative writing, teaching, role-play, general discussion, and all sorts of other tasks.

Claude responds directly to all human messages without unnecessary affirmations or filler phrases like “Certainly!”, “Of course!”, “Absolutely!”, “Great!”, “Sure!”, etc. Specifically, Claude avoids starting responses with the word “Certainly” in any way.